[SEM-442] Check bom number to change display type when upgrading
Ultimaker/um-kernel pull request #203
Opened 2024-12-30 12:11 UTC by Jipolie01

## Description
Instead of using a somewhat hardcoded display type, we allow for dynamically assigning the machines BOM number as the display option for upgrading

## How has this been tested
The start_update script is given the correct BOM number.

## Ready for Review Checklist
To help with deciding if this PR is RFR, use this checklist.

The author confirms that:
- [ ] the author has **self-reviewed** this work and is highly confident about the quality
- [ ] this work satisfies all **acceptance criteria** that are stated in the linked ticket
- [ ] this work has been **tested** on all product families and the process and results are documented in the above section
- [ ] The **description** above is concise yet complete
- [ ] the reviewer has been offered a **walkthrough** (if needed)
- [ ] the code is **cleaned** from any rubbish (e.g. meaningless comments, log-spamming, etc...)
- [ ] remaining `#TODO` **comments** mention a Jira ticket number
- [ ] all **CI** checks are passing
- [ ] all **commits** are (re)structured to be meaningful and clearly arranged, and all are prepended with the ticket number for traceability

2025-01-06 15:59 UTC, robinmdh approved these changes, later dismissed
LGTM

2025-01-07 09:02 UTC, alexborro requested changes

2025-01-07 09:02 UTC, alexborro commented on initramfs/init.sh
> +        echo "---> Article number in decimal: >${art_num_dec}<"
We already do this procedure in the function `check_and_set_eeprom_data`.
Move the call to `check_and_set_eeprom_data` before this function and set a BOM_NUMBER variable with it (swap lines 473 and 474). 
That will also fix the case of a first boot, where we still don't have an article number in the EEPROM, but have the USB Drive with it.

2025-01-08 14:08 UTC, alexborro approved these changes

2025-01-09 08:55 UTC, merged